spring:
  application:
    name: api-gateway

  
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
            - id: config-server
              uri: http://localhost:8888
              predicates:
                - Path=/config-server/**


    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/

server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
