spring:
  application:
    name: event-service
  profiles:
    active: default

# ========================
# Config Server
# ========================
  cloud:
    config:
      uri: http://localhost:8888  # Your Config Server URL
      fail-fast: true

# ========================
# Eureka Client
# ========================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# ========================
# Server Port
# ========================
server:
  port: 8071  # Event-service port

# ========================
# MongoDB Configuration
# ========================
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/eventdb

# ========================
# Redis Configuration
# ========================
spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

# ========================
# Logging
# ========================
logging:
  level:
    root: INFO
    com.event.event_service: DEBUG

# ========================
# Feign & Ribbon
# ========================
feign:
  hystrix:
    enabled: true

# ========================
# Caching (Redis)
# ========================
spring:
  cache:
    type: redis
    redis:
      time-to-live: 60000 # 60 seconds TTL for cache
      cache-null-values: false
