spring:
  application:
    name: event-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/event-service
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

logging:
  level:
    root: INFO
    com.event.event_service: DEBUG
