spring:
  application:
    name: event-service



  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


server:
  port: 8071  # Event-service port


  data:
    mongodb:
      uri: mongodb://localhost:27017/event-service


  redis:
    host: localhost
    port: 6379
    
logging:
  level:
    root: INFO
    com.event.event_service: DEBUG

feign:
  hystrix:
    enabled: true


  cache:
    type: redis
    redis:
      time-to-live: 60000 # 60 seconds TTL for cache
      cache-null-values: false
