spring:
  application:
    name: event-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/event-service
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

  redis:
    host: localhost
    port: 6379
    
logging:
  level:
    root: INFO
    com.event.event_service: DEBUG

feign:
  hystrix:
    enabled: true


  cache:
    type: redis
    redis:
      time-to-live: 60000 # 60 seconds TTL for cache
      cache-null-values: false
