server:
  port: 8084

spring:
  application:
    name: schedule-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/schedule-service
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
