spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-service
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


  redis:
    host: localhost
    port: 6379
    timeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
